[general]
import = [
    "~/.config/alacritty/flexoki-light.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
option_as_alt = "Both"
padding = {x = 0, y = 0}

[font]
size = 15.0
offset = { x = 0, y = 4 }

[font.italic]
family = "CaskaydiaMono Nerd Font Mono"

[font.bold_italic]
family = "CaskaydiaMono Nerd Font Mono"

[font.normal]
family = "CaskaydiaMono Nerd Font Mono"
style = "Light"


[cursor]
style = { shape = "Block", blinking = "Always" }
