require ("core.plugin_config.colorscheme")
require ("core.plugin_config.nvim_web_devicons")
require ("core.plugin_config.whichkey")
require ("core.plugin_config.ntree")
require ("core.plugin_config.lualine")
require ("core.plugin_config.lsp_config")
require ("core.plugin_config.treesitter")
require ("core.plugin_config.telescope_plugin")
require ("core.plugin_config.comment")
require ("core.plugin_config.autocompletion")
require ("core.plugin_config.telescope_ui_select")
require ("core.plugin_config.code_formatting")
require ("core.plugin_config.git_plugins")
-- require ("core.plugin_config.noice")
require ("core.plugin_config.harpoon")
require ("core.plugin_config.java")
require ("core.plugin_config.markdown")
require ("core.plugin_config.trouble")
