return {
	"hedyhli/outline.nvim",
	cmd = { "Outline", "OutlineOpen" },
	opts = {
		outline_window = {
			position = "right",
			width = 25,
			relative_width = true,
			auto_close = false,
			auto_jump = false,
			show_numbers = false,
			show_relative_numbers = false,
			wrap = false,
		},
		outline_items = {
			show_symbol_details = true,
			show_symbol_lineno = false,
			highlight_hovered_item = true,
			auto_set_cursor = true,
		},
		guides = {
			enabled = true,
			markers = {
				bottom = "└",
				middle = "├",
				vertical = "│",
			},
		},
		symbol_folding = {
			autofold_depth = 1,
			auto_unfold = {
				hovered = true,
				only = true,
			},
			markers = { "", "" },
		},
		preview_window = {
			auto_preview = false,
			open_hover_on_preview = false,
			width = 50,
			min_width = 50,
			relative_width = true,
			border = "rounded",
		},
		symbols = {
			filter = nil,
			icon_fetcher = nil,
			icon_source = nil,
		},
		keymaps = {
			show_help = "?",
			close = { "<Esc>", "q" },
			goto_location = "<Cr>",
			peek_location = "o",
			goto_and_close = "<S-Cr>",
			restore_location = "<C-g>",
			hover_symbol = "<C-space>",
			toggle_preview = "K",
			rename_symbol = "r",
			code_actions = "a",
			fold = "h",
			unfold = "l",
			fold_toggle = "<Tab>",
			fold_toggle_all = "<S-Tab>",
			fold_all = "W",
			unfold_all = "E",
			fold_reset = "R",
		},
	},
}
